import type { Metadata } from "next";
import { Nunito} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Newsletter from "@/components/Newsletter";
import Footer from "@/components/Footer";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

const nunito = Nunito({
  subsets: ['latin'],
  variable: '--font-nunito', 
});


export const metadata: Metadata = {
  title: "Tobams",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${nunito.variable}`}
      ><ReactQueryProvider>
        <main>
          <div>
            <Header/>
          </div>
        <div>
        {children}
        </div>
        <div>
          <Newsletter/>
        </div>
        <div>
          <Footer />
        </div>
        </main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
